# Generated by Django 4.1.6 on 2023-02-17 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('adds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.plocketuser'),
            preserve_default=False,
        ),
    ]
