name: Django Tests

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  push:
    branches:
      - main

#on:
#  schedule:
#    - cron: '*/15 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build the Stack
      run:  |
        cd ./backend
        docker-compose -f ./docker-test.yml build

    - name: Run DB Migrations
      run:  docker-compose -f ./docker-test.yml run --rm backend python manage.py migrate

    - name: Run Django Tests
      run:  docker-compose -f ./docker-test.yml run --rm backend python manage.py test

    - name: Tear down the Stack
      run:  docker-compose -f ./docker-test.yml down
